name: Peter Zaffina
description: I work with people to connect them with their data.
avatar: https://avatars.githubusercontent.com/u/38657165?v=4

url: "https://peter.zaffina.net"
baseurl: ""

permalink: /blog/:title/

footer-links:
  email: peter@zaffina.net
  github: pdzaffina
  linkedin: peter-zaffina
  dribbble:
  facebook:
  flickr:
  instagram:
  pinterest:
  rss:
  twitter:
  stackoverflow:
  youtube:
  googleplus:

disqus:
google_analytics:

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :expanded

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

collections:
  prompts:
    output: false
    sort_by: title
